name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: 
          echo "Hola mundo 1!"
          echo "Hola jonathan33!"
          echo "Hola jonathan33!"
      - name: Dime la fecha
        run: date
      - run: ls -ld